import os
from pkg_resources import resource_filename
import json
configfile: "$config"

if config['fastqs'] != None:
    path = os.path.abspath(config['fastqs'][0])
    config['input_root'] = os.path.dirname(path)
    include: resource_filename('lisa.rules', 'fastq.rule')

if config['bigwigs'] != None:
    include: resource_filename('lisa.rules', 'hdf5.rule')

if config['model']:
    include: resource_filename('lisa.rules', 'background_selection.rule')
    include: resource_filename('lisa.rules', 'model.rule')
    if not config['web']:
        include: resource_filename('lisa.rules', 'baseline.rule')

    include: resource_filename('lisa.rules', 'lisa_direct.rule')

    include: resource_filename('lisa.rules', 'knockout.rule')
    if config['cluster']:
        if not config['web']:
            include: resource_filename('lisa.rules', 'entropy.rule')

def get_targets():
    targets = []
    if config['model']:
        targets = expand("{sample}.{epigenome}.coefs.csv", sample=config["gene_sets"], epigenome=config["epigenome"]) + expand("{sample}.{epigenome}.lisa_predicted_rp.csv", sample=config["gene_sets"], epigenome=config["epigenome"])
        if not config['web']:
            targets += expand("{sample}_motif99_baseline.csv", sample=config["gene_sets"])
            targets += expand("{sample}_chipseq_baseline.csv", sample=config["gene_sets"])

        targets += expand("{sample}.lisa_direct.csv", sample=config["gene_sets"])

        targets += expand("{sample}.{epigenome}.motif99.csv", sample=config["gene_sets"], epigenome=config["epigenome"])
        targets += expand("{sample}.{epigenome}.chipseq.csv", sample=config["gene_sets"], epigenome=config["epigenome"])
        if config['cluster']:
            if not config['web']:
                targets += expand("{sample}.{epigenome}.chipseq.entropy_rank.csv", sample=config["gene_sets"], epigenome=config["epigenome"])
                targets += expand("{sample}.{epigenome}.motif99.entropy_rank.csv", sample=config["gene_sets"], epigenome=config["epigenome"])
    else:
        targets += []

    if config['fastqs'] != None:
        ## assume file as id.fastq.gz
        ids = list(map(os.path.basename, config['fastqs']))
        targets += \
                   expand('%s/%s/{sample}.bigwig' % (config['prefix'], config['epigenome']),
                          sample=ids) + \
                   expand('%s/%s/{sample}.bam' % (config['prefix'], config['epigenome']),
                          sample=ids)

    if config['bigwigs'] != None:
        targets += \
                   expand('{sample}.%s.%s.1kb_read_count.h5' % (config['prefix'], config['epigenome']),
                          sample=config['bigwigs']) + \
                    expand('{sample}.%s.%s.reg_potential.h5' % (config['prefix'], config['epigenome']),
                           sample=config['bigwigs']) + \
                   ['%s.%s.reg.h5' % (config['prefix'], config['epigenome'])] + \
                   ["%s.%s.readcount.h5" % (config['prefix'], config['epigenome'])]

        print(targets)
    return targets

rule all:
    input:
        get_targets()

rule clean:
    shell: "rm -rf *csv *performance *bench* *log *fore* *back*"
