## https://docs.anaconda.com/anaconda-cloud/user-guide/tutorials/
## https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=patchelf
package:
  name: lisa_minimal
  version: 1.0

build:
  number: 9
  binary_relocation: True

requirements:
  build:
    - python ==3.6.6
    - fire
    - setuptools
    - numpy ==1.15.1
  host:
    - python ==3.6.6
    - zlib
    - numpy ==1.15.1
  run:
    - python ==3.6.6
    - zlib
    - mkl-service
    - curl
    - fire
    - scikit-learn ==0.21.3
    - theano
    - pandas ==0.25.2
    - h5py
    - libopenblas ==0.3.3
    - numpy ==1.15.1
    - PyYAML >=3.12
    - snakemake ==5.7.1
    - yappi
    - openssl=1.0
    - mpmath

about:
  home: http://lisa.cistrome.org
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: 'ChIP-seq/DNase-seq data-driven TF and CR prioritization tool: minimal version with fewer dependency'
